//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace Assets.My_Assets.dinoScripts.search.bayesiannetwork
{
	public class Value
	{
		private string name;
		public string Name
		{
			get { return name; }
			set { this.name = value;}
		}

		private float lambdav;
		public float Lambdav
		{
			get { return lambdav; }
			set { this.lambdav = value;}
		}

		private float piv;
		public float Piv
		{
			get { return piv; }
			set { this.piv = value;}
		}

		private Dictionary<string, float> probs;
		public Dictionary<string, float> Probs
		{
			get { return probs; }
			set { this.probs = value;}
		}

		public Value (string name, Dictionary<string, float> probs)
		{
			this.name = name;
			this.lambdav = 0;
			this.piv = 0;
			this.probs = probs;
		}

		public bool Equals(Value p)
		{
			return p.name == this.name;
		}
		
		public override int GetHashCode()
		{
			return this.name.GetHashCode();
		}
	}
}
